version: "3"

name: electronic-service

volumes:
  db.data:
  data-protection-keys:

networks:
  dev:
    
services:
  webapi:
    container_name: electronics-store.webapi
    image: electronics-store.webapi
    build:
      context: .
      dockerfile: ElectronicsStore.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "5555"
    volumes:
      - data-protection-keys:/app/data-protection-keys
    ports:
      - "5555:5555"
    networks:
      - dev
    
  frontend:
    container_name: electronics-store.frontend
    image: electronics-store.frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - data-protection-keys:/app/data-protection-keys
    build:
      context: ./web_client
      dockerfile: Dockerfile
    restart: no
    ports:
      - "80:80"
    depends_on:
      - webapi
    networks:
      - dev